"""Stage 5: produce the tables and figures the report quotes.

    .venv/Scripts/python.exe scripts/05_report_artifacts.py

Nothing here trains a headline model; it measures the corpus and the split, and
runs the two experiments whose whole purpose is to be reported:

* **the leakage experiment** -- the same classifier scored on a naive random
  passage-level split and on the book-disjoint split the study actually uses.
  The gap between them is the project's central methodological claim, and it
  has to be re-measured on this corpus rather than quoted from the old one.
* **the length curve** -- accuracy against passage length, which is what tells
  a user of the demo how much text they need to paste before the answer means
  anything.

Writes into ``artifacts/tables/`` and ``artifacts/figures/``.
"""
from __future__ import annotations

import json
import pickle
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
sys.stdout.reconfigure(encoding="utf-8")

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, confusion_matrix

from banglastylo import config, corpus, evaluate, models, splits
from banglastylo.normalize import word_tokenize

T = config.TABLES
F = config.FIGURES


def corpus_stats(passages) -> pd.DataFrame:
    rows = []
    for key, meta in config.AUTHORS.items():
        ps = [p for p in passages if p.author == key]
        if not ps:
            continue
        rows.append({
            "author": meta["en"],
            "author_bn": meta["bn"],
            "years": meta["years"],
            "works": len({p.work for p in ps}),
            "chapters": len({(p.work, p.chapter) for p in ps}),
            "passages": len(ps),
            "tokens": sum(p.n_tokens for p in ps),
            "mean_passage_tokens": float(np.mean([p.n_tokens for p in ps])),
            "mean_sent_len": float(np.mean(
                [p.n_tokens / max(p.n_sentences, 1) for p in ps])),
        })
    return pd.DataFrame(rows)


def book_table(passages) -> str:
    """LaTeX table of every book, its role, and what it contributed.

    Generated rather than typed, for the same reason as every other number in
    the report: the corpus can change, and a hand-written table would go stale
    without anyone noticing.  Bengali titles are wrapped in the report's
    ``\\bn{}`` macro so they pick up the Bengali font.
    """
    prov = json.loads((config.RAW / "provenance.json").read_text(encoding="utf-8"))
    by_book: dict[str, dict[str, int]] = {}
    for pg in passages:
        agg = by_book.setdefault(pg.work, {"passages": 0, "tokens": 0})
        agg["passages"] += 1
        agg["tokens"] += pg.n_tokens

    nl = " \\\\"
    rows: list[str] = []
    for role in ("train", "unseen"):
        for key, meta in config.AUTHORS.items():
            for m in prov:
                if m["author"] != key or m["role"] != role:
                    continue
                agg = by_book.get(m["title_bn"], {"passages": 0, "tokens": 0})
                chapters = f"{m['chapters']}"
                label = "train" if role == "train" else r"\textbf{held out}"
                rows.append(
                    f"{meta['en']} & \\bn{{{m['title_bn']}}} & {label} & "
                    f"{chapters} & {agg['tokens']:,} & {agg['passages']}{nl}"
                )
        if role == "train":
            rows.append(r"\midrule")

    header = (
        r"\textbf{Author} & \textbf{Book} & \textbf{Role} & "
        r"\textbf{Chapters} & \textbf{Tokens} & \textbf{Passages}" + nl
    )
    return (
        "% Generated by scripts/05_report_artifacts.py -- do not edit by hand.\n"
        r"\begin{tabular}{lllrrr}" "\n" r"\toprule" "\n"
        + header + "\n" + r"\midrule" + "\n"
        + "\n".join(rows) + "\n"
        + r"\bottomrule" + "\n" + r"\end{tabular}" + "\n"
    )


def split_composition(split) -> pd.DataFrame:
    rows = []
    for key, meta in config.AUTHORS.items():
        row = {"author": meta["en"]}
        for name, part in (("train", split.train), ("val", split.val),
                           ("test", split.test)):
            row[name] = sum(1 for p in part if p.author == key)
        row["test_book"] = next((p.work for p in split.test if p.author == key), "")
        rows.append(row)
    return pd.DataFrame(rows)


def leakage_experiment(passages, split) -> dict:
    """Score one model two ways: random passages vs whole held-out books.

    The random split is the *wrong* protocol, reproduced deliberately.  It
    shuffles passages without regard to which book they came from, so passages
    from the test book sit in training and the classifier can recognise a
    character name instead of a style.  Reporting both numbers is the only way
    to show how much of an attribution score is style and how much is topic.
    """
    import random

    train_pool = [p for p in passages if p.role != "unseen"]
    unseen = [p for p in passages if p.role == "unseen"]

    # --- the honest protocol: train on training books, test on held-out books
    xtr, ytr = [p.text for p in train_pool], [p.author for p in train_pool]
    xte, yte = [p.text for p in split.test], [p.author for p in split.test]
    pipe = models.build_svm_pipeline()
    pipe.fit(xtr, ytr)
    work_acc = accuracy_score(yte, pipe.predict(xte))

    # --- the leaky protocol: pool everything, shuffle, split by passage
    allp = train_pool + unseen
    rng = random.Random(config.SEED)
    idx = list(range(len(allp)))
    rng.shuffle(idx)
    cut = int(0.75 * len(idx))
    tr = [allp[i] for i in idx[:cut]]
    te = [allp[i] for i in idx[cut:]]
    pipe2 = models.build_svm_pipeline()
    pipe2.fit([p.text for p in tr], [p.author for p in tr])
    rand_acc = accuracy_score([p.author for p in te],
                              pipe2.predict([p.text for p in te]))

    return {
        "model": "SVM over all stylometric families",
        "work_disjoint_accuracy": float(work_acc),
        "random_split_accuracy": float(rand_acc),
        "leakage_inflation": float(rand_acc - work_acc),
        "n_train_random": len(tr),
        "n_test_random": len(te),
        "note": ("the random split lets passages from a held-out book appear in "
                 "training; the gap is the part of the score that is topic, not "
                 "style"),
    }


def length_curve(split) -> pd.DataFrame:
    """Accuracy as a function of how much text the model is shown."""
    xtr, ytr = splits.xy(split.train)
    gen = models.GenerativeAttributor(level="char").fit(xtr, ytr, verbose=False)
    disc = models.build_svm_pipeline().fit(xtr, ytr)

    rows = []
    for n in (20, 40, 60, 80, 120, 160):
        trimmed, truth = [], []
        for p in split.test:
            toks = word_tokenize(p.text)
            if len(toks) < n:
                continue
            trimmed.append(" ".join(toks[:n]))
            truth.append(p.author)
        if len(trimmed) < 30:
            continue
        rows.append({
            "tokens": n,
            "n": len(trimmed),
            "generative": float(accuracy_score(truth, gen.predict(trimmed))),
            "discriminative": float(accuracy_score(truth, disc.predict(trimmed))),
        })
    return pd.DataFrame(rows)


def paradigm_agreement(split) -> pd.DataFrame:
    xtr, ytr = splits.xy(split.train)
    xte, yte = splits.xy(split.test)
    gen = models.GenerativeAttributor(level="char").fit(xtr, ytr, verbose=False)
    disc = models.build_svm_pipeline().fit(xtr, ytr)
    g, d = gen.predict(xte), disc.predict(xte)
    counts = Counter()
    for truth, gp, dp in zip(yte, g, d):
        if gp == dp:
            counts["agree, both correct" if gp == truth else "agree, both wrong"] += 1
        elif dp == truth:
            counts["disagree, discriminative correct"] += 1
        elif gp == truth:
            counts["disagree, generative correct"] += 1
        else:
            counts["disagree, both wrong"] += 1
    return pd.DataFrame(sorted(counts.items()), columns=["case", "n"])


def confusion_figure(split) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    xte, yte = splits.xy(split.test)
    order = sorted(set(yte))
    names = [evaluate.short(a) for a in order]

    # 1. TF-IDF + SVM
    tfidf_path = config.MODELS / "tfidf_svm.pkl"
    if tfidf_path.exists():
        with open(tfidf_path, "rb") as f:
            tfidf_model = pickle.load(f)
        tfidf_pred = tfidf_model.predict(xte)
    else:
        xtr, ytr = splits.xy(split.train)
        tfidf_model = models.build_tfidf_baseline().fit(xtr, ytr)
        tfidf_pred = tfidf_model.predict(xte)
    cm_tfidf = confusion_matrix(yte, tfidf_pred, labels=order)
    acc_tfidf = accuracy_score(yte, tfidf_pred)

    # 2. BiLSTM & 3. BanglaBERT from Kaggle results
    gpu_path = config.ARTIFACTS / "kaggle" / "gpu_results.json"
    if gpu_path.exists():
        gpu = json.loads(gpu_path.read_text(encoding="utf-8"))
        bilstm_pred = gpu["bilstm"]["predictions"]
        bert_pred = gpu["banglabert_finetuned"]["predictions"]
        cm_bilstm = confusion_matrix(yte, bilstm_pred, labels=order)
        cm_bert = confusion_matrix(yte, bert_pred, labels=order)
        acc_bilstm = accuracy_score(yte, bilstm_pred)
        acc_bert = accuracy_score(yte, bert_pred)
    else:
        cm_bilstm = cm_tfidf
        cm_bert = cm_tfidf
        acc_bilstm = acc_tfidf
        acc_bert = acc_tfidf

    cms = [
        (f"TF-IDF + SVM ({acc_tfidf * 100:.1f}%)", cm_tfidf),
        (f"BiLSTM ({acc_bilstm * 100:.1f}%)", cm_bilstm),
        (f"BanglaBERT ({acc_bert * 100:.1f}%)", cm_bert),
    ]

    fig, axes = plt.subplots(1, 3, figsize=(11.5, 3.6), sharey=True)
    for ax, (title, cm) in zip(axes, cms):
        ax.imshow(cm, cmap="Blues", vmin=0, vmax=180)
        ax.set_xticks(range(len(names)))
        ax.set_xticklabels(names, rotation=25, ha="right", fontsize=9)
        ax.set_yticks(range(len(names)))
        ax.set_yticklabels(names, fontsize=9)
        ax.set_xlabel("Predicted", fontsize=10)
        ax.set_title(title, fontsize=11, fontweight="bold", pad=8)
        for i in range(len(names)):
            for j in range(len(names)):
                val = cm[i, j]
                color = "white" if val > 90 else "black"
                ax.text(j, i, str(val), ha="center", va="center", color=color,
                        fontsize=10, fontweight="bold" if i == j else "normal")

    axes[0].set_ylabel("True", fontsize=10)
    fig.tight_layout()
    for target in (F / "confusion_models.png",
                   config.REPORT_FIGURES / "confusion_models.png"):
        fig.savefig(target, dpi=200, bbox_inches="tight")
    plt.close(fig)


def main() -> int:
    passages = corpus.load_passages()
    split = splits.load(passages)

    print("=== corpus stats ===")
    cs = corpus_stats(passages)
    cs.to_csv(T / "corpus_stats.csv", index=False)
    print(cs.to_string(index=False))

    print("\n=== per-book table ===")
    (T / "corpus_books.tex").write_text(book_table(passages), encoding="utf-8")
    print(f"  wrote {T / 'corpus_books.tex'}")

    print("\n=== split composition ===")
    sc = split_composition(split)
    sc.to_csv(T / "split_composition.csv", index=False)
    print(sc.to_string(index=False))

    print("\n=== leakage experiment (this is the headline methodology) ===")
    leak = leakage_experiment(passages, split)
    (T / "leakage_experiment.json").write_text(
        json.dumps(leak, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"  book-disjoint (honest) : {leak['work_disjoint_accuracy']:.4f}")
    print(f"  random passage split   : {leak['random_split_accuracy']:.4f}")
    print(f"  inflation from leakage : {leak['leakage_inflation']:+.4f}")

    print("\n=== POS tagger on UD_Bengali-BRU ===")
    ud = config.RAW / "bn_bru-ud-test.conllu"
    if ud.exists():
        from banglastylo import postag
        pos = postag.evaluate_on_ud(ud)
        (T / "postag_eval.json").write_text(
            json.dumps(pos, ensure_ascii=False, indent=2), encoding="utf-8")
        print(f"  accuracy {pos['accuracy']:.4f} on {pos['n_tokens']} tokens")
    else:
        print(f"  skipped: {ud} not present")

    print("\n=== paradigm agreement ===")
    pa = paradigm_agreement(split)
    pa.to_csv(T / "paradigm_agreement.csv", index=False)
    print(pa.to_string(index=False))

    print("\n=== length curve ===")
    lc = length_curve(split)
    lc.to_csv(T / "length_curve.csv", index=False)
    print(lc.to_string(index=False))

    print("\n=== figures ===")
    confusion_figure(split)
    print(f"  wrote {F / 'confusion_models.png'}")
    print(f"  wrote {config.REPORT_FIGURES / 'confusion_models.png'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
